"""essage=relation between user and project

Revision ID: 0abe31a480cf
Revises: 542082b1b1c7
Create Date: 2025-03-13 22:37:16.517327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0abe31a480cf'
down_revision: Union[str, None] = '542082b1b1c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assignee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['assignee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'assignee_id')
    # ### end Alembic commands ###
