"""empty message

Revision ID: f6f5ef124d79
Revises: 0abe31a480cf
Create Date: 2025-03-31 18:01:41.244557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f5ef124d79'
down_revision: Union[str, None] = '0abe31a480cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_on', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('deadline', sa.Date(), nullable=True))
    op.add_column('projects', sa.Column('author', sa.Integer(), nullable=True))
    op.drop_index('ix_projects_id', table_name='projects')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_constraint('projects_assignee_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['author'], ['id'])
    op.drop_column('projects', 'assignee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assignee_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_assignee_id_fkey', 'projects', 'users', ['assignee_id'], ['id'])
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.drop_column('projects', 'author')
    op.drop_column('projects', 'deadline')
    op.drop_column('projects', 'created_on')
    # ### end Alembic commands ###
